execute @a[scores={t=2}] ~ ~ ~ fill ~ ~-2 ~ ~8 ~-2 ~16 chest
tp @a[scores={t=..161}] ~ ~1 ~
execute @a[scores={t=41}] ~ ~ ~ function chemistry/chemical_heat
execute @a[scores={t=42}] ~ ~ ~ function chemistry/chemistry_table
execute @a[scores={t=43}] ~ ~ ~ function chemistry/colored_torch_bp
execute @a[scores={t=44}] ~ ~ ~ function chemistry/colored_torch_rg
execute @a[scores={t=45}] ~ ~ ~ function chemistry/element_0
execute @a[scores={t=46}] ~ ~ ~ function chemistry/element_1
execute @a[scores={t=47}] ~ ~ ~ function chemistry/element_10
execute @a[scores={t=48}] ~ ~ ~ function chemistry/element_100
execute @a[scores={t=49}] ~ ~ ~ function chemistry/element_101
execute @a[scores={t=50}] ~ ~ ~ function chemistry/element_102
execute @a[scores={t=51}] ~ ~ ~ function chemistry/element_103
execute @a[scores={t=52}] ~ ~ ~ function chemistry/element_104
execute @a[scores={t=53}] ~ ~ ~ function chemistry/element_105
execute @a[scores={t=54}] ~ ~ ~ function chemistry/element_106
execute @a[scores={t=55}] ~ ~ ~ function chemistry/element_107
execute @a[scores={t=56}] ~ ~ ~ function chemistry/element_108
execute @a[scores={t=56}] ~ ~ ~ function chemistry/element_109
execute @a[scores={t=57}] ~ ~ ~ function chemistry/element_11
execute @a[scores={t=58}] ~ ~ ~ function chemistry/element_110
execute @a[scores={t=59}] ~ ~ ~ function chemistry/element_111
execute @a[scores={t=60}] ~ ~ ~ function chemistry/element_112
execute @a[scores={t=61}] ~ ~ ~ function chemistry/element_113
execute @a[scores={t=62}] ~ ~ ~ function chemistry/element_114
execute @a[scores={t=63}] ~ ~ ~ function chemistry/element_115
execute @a[scores={t=64}] ~ ~ ~ function chemistry/element_116
execute @a[scores={t=65}] ~ ~ ~ function chemistry/element_117
execute @a[scores={t=66}] ~ ~ ~ function chemistry/element_118
execute @a[scores={t=67}] ~ ~ ~ function chemistry/element_12
execute @a[scores={t=68}] ~ ~ ~ function chemistry/element_13
execute @a[scores={t=69}] ~ ~ ~ function chemistry/element_14
execute @a[scores={t=70}] ~ ~ ~ function chemistry/element_15
execute @a[scores={t=71}] ~ ~ ~ function chemistry/element_16
execute @a[scores={t=72}] ~ ~ ~ function chemistry/element_17
execute @a[scores={t=72}] ~ ~ ~ function chemistry/element_18
execute @a[scores={t=73}] ~ ~ ~ function chemistry/element_19
execute @a[scores={t=74}] ~ ~ ~ function chemistry/element_2
execute @a[scores={t=75}] ~ ~ ~ function chemistry/element_20
execute @a[scores={t=76}] ~ ~ ~ function chemistry/element_21
execute @a[scores={t=77}] ~ ~ ~ function chemistry/element_22
execute @a[scores={t=78}] ~ ~ ~ function chemistry/element_23
execute @a[scores={t=79}] ~ ~ ~ function chemistry/element_24
execute @a[scores={t=80}] ~ ~ ~ function chemistry/element_25
execute @a[scores={t=81}] ~ ~ ~ function chemistry/element_26
execute @a[scores={t=82}] ~ ~ ~ function chemistry/element_27
execute @a[scores={t=83}] ~ ~ ~ function chemistry/element_28
execute @a[scores={t=84}] ~ ~ ~ function chemistry/element_29
execute @a[scores={t=85}] ~ ~ ~ function chemistry/element_3
execute @a[scores={t=86}] ~ ~ ~ function chemistry/element_30
execute @a[scores={t=87}] ~ ~ ~ function chemistry/element_31
execute @a[scores={t=88}] ~ ~ ~ function chemistry/element_32
execute @a[scores={t=88}] ~ ~ ~ function chemistry/element_33
execute @a[scores={t=89}] ~ ~ ~ function chemistry/element_34
execute @a[scores={t=90}] ~ ~ ~ function chemistry/element_35
execute @a[scores={t=91}] ~ ~ ~ function chemistry/element_36
execute @a[scores={t=92}] ~ ~ ~ function chemistry/element_37
execute @a[scores={t=93}] ~ ~ ~ function chemistry/element_38
execute @a[scores={t=94}] ~ ~ ~ function chemistry/element_39
execute @a[scores={t=95}] ~ ~ ~ function chemistry/element_4
execute @a[scores={t=96}] ~ ~ ~ function chemistry/element_40
execute @a[scores={t=97}] ~ ~ ~ function chemistry/element_41
execute @a[scores={t=98}] ~ ~ ~ function chemistry/element_42
execute @a[scores={t=99}] ~ ~ ~ function chemistry/element_43
execute @a[scores={t=100}] ~ ~ ~ function chemistry/element_44
execute @a[scores={t=101}] ~ ~ ~ function chemistry/element_45
execute @a[scores={t=102}] ~ ~ ~ function chemistry/element_46
execute @a[scores={t=103}] ~ ~ ~ function chemistry/element_47
execute @a[scores={t=104}] ~ ~ ~ function chemistry/element_48
execute @a[scores={t=104}] ~ ~ ~ function chemistry/element_49
execute @a[scores={t=105}] ~ ~ ~ function chemistry/element_5
execute @a[scores={t=106}] ~ ~ ~ function chemistry/element_50
execute @a[scores={t=107}] ~ ~ ~ function chemistry/element_51
execute @a[scores={t=108}] ~ ~ ~ function chemistry/element_52
execute @a[scores={t=109}] ~ ~ ~ function chemistry/element_53
execute @a[scores={t=110}] ~ ~ ~ function chemistry/element_54
execute @a[scores={t=111}] ~ ~ ~ function chemistry/element_55
execute @a[scores={t=112}] ~ ~ ~ function chemistry/element_56
execute @a[scores={t=113}] ~ ~ ~ function chemistry/element_57
execute @a[scores={t=114}] ~ ~ ~ function chemistry/element_58
execute @a[scores={t=115}] ~ ~ ~ function chemistry/element_59
execute @a[scores={t=116}] ~ ~ ~ function chemistry/element_6
execute @a[scores={t=117}] ~ ~ ~ function chemistry/element_60
execute @a[scores={t=118}] ~ ~ ~ function chemistry/element_61
execute @a[scores={t=119}] ~ ~ ~ function chemistry/element_62
execute @a[scores={t=120}] ~ ~ ~ function chemistry/element_63
execute @a[scores={t=120}] ~ ~ ~ function chemistry/element_64
execute @a[scores={t=121}] ~ ~ ~ function chemistry/element_65
execute @a[scores={t=122}] ~ ~ ~ function chemistry/element_66
execute @a[scores={t=123}] ~ ~ ~ function chemistry/element_67
execute @a[scores={t=124}] ~ ~ ~ function chemistry/element_68
execute @a[scores={t=125}] ~ ~ ~ function chemistry/element_69
execute @a[scores={t=126}] ~ ~ ~ function chemistry/element_7
execute @a[scores={t=127}] ~ ~ ~ function chemistry/element_70
execute @a[scores={t=128}] ~ ~ ~ function chemistry/element_71
execute @a[scores={t=129}] ~ ~ ~ function chemistry/element_72
execute @a[scores={t=130}] ~ ~ ~ function chemistry/element_73
execute @a[scores={t=131}] ~ ~ ~ function chemistry/element_74
execute @a[scores={t=132}] ~ ~ ~ function chemistry/element_75
execute @a[scores={t=133}] ~ ~ ~ function chemistry/element_76
execute @a[scores={t=134}] ~ ~ ~ function chemistry/element_77
execute @a[scores={t=135}] ~ ~ ~ function chemistry/element_78
execute @a[scores={t=136}] ~ ~ ~ function chemistry/element_79
execute @a[scores={t=136}] ~ ~ ~ function chemistry/element_8
execute @a[scores={t=137}] ~ ~ ~ function chemistry/element_80
execute @a[scores={t=138}] ~ ~ ~ function chemistry/element_81
execute @a[scores={t=139}] ~ ~ ~ function chemistry/element_82
execute @a[scores={t=140}] ~ ~ ~ function chemistry/element_83
execute @a[scores={t=141}] ~ ~ ~ function chemistry/element_84
execute @a[scores={t=142}] ~ ~ ~ function chemistry/element_85
execute @a[scores={t=143}] ~ ~ ~ function chemistry/element_86
execute @a[scores={t=144}] ~ ~ ~ function chemistry/element_87
execute @a[scores={t=145}] ~ ~ ~ function chemistry/element_88
execute @a[scores={t=146}] ~ ~ ~ function chemistry/element_89
execute @a[scores={t=147}] ~ ~ ~ function chemistry/element_9
execute @a[scores={t=148}] ~ ~ ~ function chemistry/element_90
execute @a[scores={t=149}] ~ ~ ~ function chemistry/element_91
execute @a[scores={t=150}] ~ ~ ~ function chemistry/element_92
execute @a[scores={t=151}] ~ ~ ~ function chemistry/element_93
execute @a[scores={t=152}] ~ ~ ~ function chemistry/element_94
execute @a[scores={t=152}] ~ ~ ~ function chemistry/element_95
execute @a[scores={t=153}] ~ ~ ~ function chemistry/element_96
execute @a[scores={t=154}] ~ ~ ~ function chemistry/element_97
execute @a[scores={t=155}] ~ ~ ~ function chemistry/element_98
execute @a[scores={t=156}] ~ ~ ~ function chemistry/element_99
execute @a[scores={t=157}] ~ ~ ~ function chemistry/hard_glass
execute @a[scores={t=158}] ~ ~ ~ function chemistry/hard_glass_pane
execute @a[scores={t=159}] ~ ~ ~ function chemistry/hard_stained_glass
execute @a[scores={t=160}] ~ ~ ~ function chemistry/hard_stained_glass_pane
execute @a[scores={t=161}] ~ ~ ~ function chemistry/underwater_torch
scoreboard players add @a t 1