execute @a[scores={t=2}] ~ ~ ~ fill ~ ~-2 ~ ~20 ~-2 ~16 chest
tp @a[scores={t=..344}] ~ ~1 ~
execute @a[scores={t=41}] ~ ~ ~ function vanilla/acacia_button
execute @a[scores={t=42}] ~ ~ ~ function vanilla/acacia_door
execute @a[scores={t=43}] ~ ~ ~ function vanilla/acacia_fence_gate
execute @a[scores={t=44}] ~ ~ ~ function vanilla/acacia_pressure_plate
execute @a[scores={t=45}] ~ ~ ~ function vanilla/acacia_stairs
execute @a[scores={t=46}] ~ ~ ~ function vanilla/acacia_standing_sign
execute @a[scores={t=47}] ~ ~ ~ function vanilla/acacia_trapdoor
execute @a[scores={t=48}] ~ ~ ~ function vanilla/acacia_wall_sign
execute @a[scores={t=49}] ~ ~ ~ function vanilla/activator_rail
execute @a[scores={t=50}] ~ ~ ~ function vanilla/air
execute @a[scores={t=51}] ~ ~ ~ function vanilla/andesite_stairs
execute @a[scores={t=52}] ~ ~ ~ function vanilla/anvil
execute @a[scores={t=53}] ~ ~ ~ function vanilla/bamboo
execute @a[scores={t=54}] ~ ~ ~ function vanilla/bamboo_sapling
execute @a[scores={t=55}] ~ ~ ~ function vanilla/barrel
execute @a[scores={t=56}] ~ ~ ~ function vanilla/barrier
execute @a[scores={t=56}] ~ ~ ~ function vanilla/beacon
execute @a[scores={t=57}] ~ ~ ~ function vanilla/bed
execute @a[scores={t=58}] ~ ~ ~ function vanilla/bedrock
execute @a[scores={t=59}] ~ ~ ~ function vanilla/beetroot
execute @a[scores={t=60}] ~ ~ ~ function vanilla/bell
execute @a[scores={t=61}] ~ ~ ~ function vanilla/birch_button
execute @a[scores={t=62}] ~ ~ ~ function vanilla/birch_door
execute @a[scores={t=63}] ~ ~ ~ function vanilla/birch_fence_gate
execute @a[scores={t=64}] ~ ~ ~ function vanilla/birch_pressure_plate
execute @a[scores={t=65}] ~ ~ ~ function vanilla/birch_stairs
execute @a[scores={t=66}] ~ ~ ~ function vanilla/birch_standing_sign
execute @a[scores={t=67}] ~ ~ ~ function vanilla/birch_trapdoor
execute @a[scores={t=68}] ~ ~ ~ function vanilla/birch_wall_sign
execute @a[scores={t=69}] ~ ~ ~ function vanilla/black_glazed_terracotta
execute @a[scores={t=70}] ~ ~ ~ function vanilla/blast_furnace
execute @a[scores={t=71}] ~ ~ ~ function vanilla/blue_glazed_terracotta
execute @a[scores={t=72}] ~ ~ ~ function vanilla/blue_ice
execute @a[scores={t=72}] ~ ~ ~ function vanilla/bone_block
execute @a[scores={t=73}] ~ ~ ~ function vanilla/bookshelf
execute @a[scores={t=74}] ~ ~ ~ function vanilla/brewing_stand
execute @a[scores={t=75}] ~ ~ ~ function vanilla/brick_block
execute @a[scores={t=76}] ~ ~ ~ function vanilla/brick_stairs
execute @a[scores={t=77}] ~ ~ ~ function vanilla/brown_glazed_terracotta
execute @a[scores={t=78}] ~ ~ ~ function vanilla/brown_mushroom
execute @a[scores={t=79}] ~ ~ ~ function vanilla/brown_mushroom_block
execute @a[scores={t=80}] ~ ~ ~ function vanilla/bubble_column
execute @a[scores={t=81}] ~ ~ ~ function vanilla/cactus
execute @a[scores={t=82}] ~ ~ ~ function vanilla/cake
execute @a[scores={t=83}] ~ ~ ~ function vanilla/carpet
execute @a[scores={t=84}] ~ ~ ~ function vanilla/carrots
execute @a[scores={t=85}] ~ ~ ~ function vanilla/cartography_table
execute @a[scores={t=86}] ~ ~ ~ function vanilla/carved_pumpkin
execute @a[scores={t=87}] ~ ~ ~ function vanilla/cauldron
execute @a[scores={t=88}] ~ ~ ~ function vanilla/chain_command_block
execute @a[scores={t=88}] ~ ~ ~ function vanilla/chest
execute @a[scores={t=89}] ~ ~ ~ function vanilla/chorus_flower
execute @a[scores={t=90}] ~ ~ ~ function vanilla/chorus_plant
execute @a[scores={t=91}] ~ ~ ~ function vanilla/clay
execute @a[scores={t=92}] ~ ~ ~ function vanilla/coal_block
execute @a[scores={t=93}] ~ ~ ~ function vanilla/coal_ore
execute @a[scores={t=94}] ~ ~ ~ function vanilla/cobblestone
execute @a[scores={t=95}] ~ ~ ~ function vanilla/cobblestone_wall
execute @a[scores={t=96}] ~ ~ ~ function vanilla/cocoa
execute @a[scores={t=97}] ~ ~ ~ function vanilla/command_block
execute @a[scores={t=98}] ~ ~ ~ function vanilla/concrete
execute @a[scores={t=99}] ~ ~ ~ function vanilla/concretePowder
execute @a[scores={t=100}] ~ ~ ~ function vanilla/conduit
execute @a[scores={t=101}] ~ ~ ~ function vanilla/coral
execute @a[scores={t=102}] ~ ~ ~ function vanilla/coral_block
execute @a[scores={t=103}] ~ ~ ~ function vanilla/coral_fan
execute @a[scores={t=104}] ~ ~ ~ function vanilla/coral_fan_dead
execute @a[scores={t=104}] ~ ~ ~ function vanilla/coral_fan_hang
execute @a[scores={t=105}] ~ ~ ~ function vanilla/coral_fan_hang2
execute @a[scores={t=106}] ~ ~ ~ function vanilla/coral_fan_hang3
execute @a[scores={t=107}] ~ ~ ~ function vanilla/crafting_table
execute @a[scores={t=108}] ~ ~ ~ function vanilla/cyan_glazed_terracotta
execute @a[scores={t=109}] ~ ~ ~ function vanilla/dark_oak_button
execute @a[scores={t=110}] ~ ~ ~ function vanilla/dark_oak_door
execute @a[scores={t=111}] ~ ~ ~ function vanilla/dark_oak_fence_gate
execute @a[scores={t=112}] ~ ~ ~ function vanilla/dark_oak_pressure_plate
execute @a[scores={t=113}] ~ ~ ~ function vanilla/dark_oak_stairs
execute @a[scores={t=114}] ~ ~ ~ function vanilla/dark_oak_trapdoor
execute @a[scores={t=115}] ~ ~ ~ function vanilla/dark_prismarine_stairs
execute @a[scores={t=116}] ~ ~ ~ function vanilla/darkoak_standing_sign
execute @a[scores={t=117}] ~ ~ ~ function vanilla/darkoak_wall_sign
execute @a[scores={t=118}] ~ ~ ~ function vanilla/daylight_detector
execute @a[scores={t=119}] ~ ~ ~ function vanilla/daylight_detector_inverted
execute @a[scores={t=120}] ~ ~ ~ function vanilla/deadbush
execute @a[scores={t=120}] ~ ~ ~ function vanilla/detector_rail
execute @a[scores={t=121}] ~ ~ ~ function vanilla/diamond_block
execute @a[scores={t=122}] ~ ~ ~ function vanilla/diamond_ore
execute @a[scores={t=123}] ~ ~ ~ function vanilla/diorite_stairs
execute @a[scores={t=124}] ~ ~ ~ function vanilla/dirt
execute @a[scores={t=125}] ~ ~ ~ function vanilla/dispenser
execute @a[scores={t=126}] ~ ~ ~ function vanilla/double_plant
execute @a[scores={t=127}] ~ ~ ~ function vanilla/double_stone_slab
execute @a[scores={t=128}] ~ ~ ~ function vanilla/double_stone_slab2
execute @a[scores={t=129}] ~ ~ ~ function vanilla/double_stone_slab3
execute @a[scores={t=130}] ~ ~ ~ function vanilla/double_stone_slab4
execute @a[scores={t=131}] ~ ~ ~ function vanilla/double_wooden_slab
execute @a[scores={t=132}] ~ ~ ~ function vanilla/dragon_egg
execute @a[scores={t=133}] ~ ~ ~ function vanilla/dried_kelp_block
execute @a[scores={t=134}] ~ ~ ~ function vanilla/dropper
execute @a[scores={t=135}] ~ ~ ~ function vanilla/emerald_block
execute @a[scores={t=136}] ~ ~ ~ function vanilla/emerald_ore
execute @a[scores={t=136}] ~ ~ ~ function vanilla/enchanting_table
execute @a[scores={t=137}] ~ ~ ~ function vanilla/end_brick_stairs
execute @a[scores={t=138}] ~ ~ ~ function vanilla/end_bricks
execute @a[scores={t=139}] ~ ~ ~ function vanilla/end_gateway
execute @a[scores={t=140}] ~ ~ ~ function vanilla/end_portal
execute @a[scores={t=141}] ~ ~ ~ function vanilla/end_portal_frame
execute @a[scores={t=142}] ~ ~ ~ function vanilla/end_rod
execute @a[scores={t=143}] ~ ~ ~ function vanilla/end_stone
execute @a[scores={t=144}] ~ ~ ~ function vanilla/ender_chest
execute @a[scores={t=145}] ~ ~ ~ function vanilla/farmland
execute @a[scores={t=146}] ~ ~ ~ function vanilla/fence
execute @a[scores={t=147}] ~ ~ ~ function vanilla/fence_gate
execute @a[scores={t=148}] ~ ~ ~ function vanilla/fire
execute @a[scores={t=149}] ~ ~ ~ function vanilla/fletching_table
execute @a[scores={t=150}] ~ ~ ~ function vanilla/flower_pot
execute @a[scores={t=151}] ~ ~ ~ function vanilla/flowing_lava
execute @a[scores={t=152}] ~ ~ ~ function vanilla/flowing_water
execute @a[scores={t=152}] ~ ~ ~ function vanilla/frame
execute @a[scores={t=153}] ~ ~ ~ function vanilla/frosted_ice
execute @a[scores={t=154}] ~ ~ ~ function vanilla/furnace
execute @a[scores={t=155}] ~ ~ ~ function vanilla/glass
execute @a[scores={t=156}] ~ ~ ~ function vanilla/glass_pane
execute @a[scores={t=157}] ~ ~ ~ function vanilla/glowingobsidian
execute @a[scores={t=158}] ~ ~ ~ function vanilla/glowstone
execute @a[scores={t=159}] ~ ~ ~ function vanilla/gold_block
execute @a[scores={t=160}] ~ ~ ~ function vanilla/gold_ore
execute @a[scores={t=161}] ~ ~ ~ function vanilla/golden_rail
execute @a[scores={t=162}] ~ ~ ~ function vanilla/granite_stairs
execute @a[scores={t=163}] ~ ~ ~ function vanilla/grass
execute @a[scores={t=164}] ~ ~ ~ function vanilla/grass_path
execute @a[scores={t=165}] ~ ~ ~ function vanilla/gravel
execute @a[scores={t=166}] ~ ~ ~ function vanilla/gray_glazed_terracotta
execute @a[scores={t=167}] ~ ~ ~ function vanilla/green_glazed_terracotta
execute @a[scores={t=168}] ~ ~ ~ function vanilla/grindstone
execute @a[scores={t=168}] ~ ~ ~ function vanilla/hardened_clay
execute @a[scores={t=169}] ~ ~ ~ function vanilla/hay_block
execute @a[scores={t=170}] ~ ~ ~ function vanilla/heavy_weighted_pressure_plate
execute @a[scores={t=171}] ~ ~ ~ function vanilla/hopper
execute @a[scores={t=172}] ~ ~ ~ function vanilla/ice
execute @a[scores={t=173}] ~ ~ ~ function vanilla/info_update
execute @a[scores={t=174}] ~ ~ ~ function vanilla/info_update2
execute @a[scores={t=175}] ~ ~ ~ function vanilla/invisibleBedrock
execute @a[scores={t=176}] ~ ~ ~ function vanilla/iron_bars
execute @a[scores={t=177}] ~ ~ ~ function vanilla/iron_block
execute @a[scores={t=178}] ~ ~ ~ function vanilla/iron_door
execute @a[scores={t=179}] ~ ~ ~ function vanilla/iron_ore
execute @a[scores={t=180}] ~ ~ ~ function vanilla/iron_trapdoor
execute @a[scores={t=181}] ~ ~ ~ function vanilla/jukebox
execute @a[scores={t=182}] ~ ~ ~ function vanilla/jungle_button
execute @a[scores={t=183}] ~ ~ ~ function vanilla/jungle_door
execute @a[scores={t=184}] ~ ~ ~ function vanilla/jungle_fence_gate
execute @a[scores={t=184}] ~ ~ ~ function vanilla/jungle_pressure_plate
execute @a[scores={t=185}] ~ ~ ~ function vanilla/jungle_stairs
execute @a[scores={t=186}] ~ ~ ~ function vanilla/jungle_standing_sign
execute @a[scores={t=187}] ~ ~ ~ function vanilla/jungle_trapdoor
execute @a[scores={t=188}] ~ ~ ~ function vanilla/jungle_wall_sign
execute @a[scores={t=189}] ~ ~ ~ function vanilla/kelp
execute @a[scores={t=190}] ~ ~ ~ function vanilla/ladder
execute @a[scores={t=191}] ~ ~ ~ function vanilla/lantern
execute @a[scores={t=192}] ~ ~ ~ function vanilla/lapis_block
execute @a[scores={t=193}] ~ ~ ~ function vanilla/lapis_ore
execute @a[scores={t=194}] ~ ~ ~ function vanilla/lava
execute @a[scores={t=195}] ~ ~ ~ function vanilla/lava_cauldron
execute @a[scores={t=196}] ~ ~ ~ function vanilla/leaves
execute @a[scores={t=197}] ~ ~ ~ function vanilla/leaves2
execute @a[scores={t=198}] ~ ~ ~ function vanilla/lever
execute @a[scores={t=199}] ~ ~ ~ function vanilla/light_blue_glazed_terracotta
execute @a[scores={t=200}] ~ ~ ~ function vanilla/light_weighted_pressure_plate
execute @a[scores={t=200}] ~ ~ ~ function vanilla/lime_glazed_terracotta
execute @a[scores={t=201}] ~ ~ ~ function vanilla/lit_furnace
execute @a[scores={t=202}] ~ ~ ~ function vanilla/lit_pumpkin
execute @a[scores={t=203}] ~ ~ ~ function vanilla/lit_redstone_lamp
execute @a[scores={t=204}] ~ ~ ~ function vanilla/lit_redstone_ore
execute @a[scores={t=205}] ~ ~ ~ function vanilla/log
execute @a[scores={t=206}] ~ ~ ~ function vanilla/log2
execute @a[scores={t=207}] ~ ~ ~ function vanilla/magenta_glazed_terracotta
execute @a[scores={t=208}] ~ ~ ~ function vanilla/magma
execute @a[scores={t=209}] ~ ~ ~ function vanilla/melon_block
execute @a[scores={t=210}] ~ ~ ~ function vanilla/melon_stem
execute @a[scores={t=211}] ~ ~ ~ function vanilla/mob_spawner
execute @a[scores={t=212}] ~ ~ ~ function vanilla/monster_egg
execute @a[scores={t=213}] ~ ~ ~ function vanilla/mossy_cobblestone
execute @a[scores={t=214}] ~ ~ ~ function vanilla/mossy_cobblestone_stairs
execute @a[scores={t=215}] ~ ~ ~ function vanilla/mossy_stone_brick_stairs
execute @a[scores={t=216}] ~ ~ ~ function vanilla/movingBlock
execute @a[scores={t=216}] ~ ~ ~ function vanilla/mycelium
execute @a[scores={t=217}] ~ ~ ~ function vanilla/nether_brick
execute @a[scores={t=218}] ~ ~ ~ function vanilla/nether_brick_fence
execute @a[scores={t=219}] ~ ~ ~ function vanilla/nether_brick_stairs
execute @a[scores={t=220}] ~ ~ ~ function vanilla/nether_wart
execute @a[scores={t=221}] ~ ~ ~ function vanilla/nether_wart_block
execute @a[scores={t=222}] ~ ~ ~ function vanilla/netherrack
execute @a[scores={t=223}] ~ ~ ~ function vanilla/netherreactor
execute @a[scores={t=224}] ~ ~ ~ function vanilla/normal_stone_stairs
execute @a[scores={t=225}] ~ ~ ~ function vanilla/noteblock
execute @a[scores={t=226}] ~ ~ ~ function vanilla/oak_stairs
execute @a[scores={t=227}] ~ ~ ~ function vanilla/observer
execute @a[scores={t=228}] ~ ~ ~ function vanilla/obsidian
execute @a[scores={t=229}] ~ ~ ~ function vanilla/orange_glazed_terracotta
execute @a[scores={t=230}] ~ ~ ~ function vanilla/packed_ice
execute @a[scores={t=231}] ~ ~ ~ function vanilla/pink_glazed_terracotta
execute @a[scores={t=232}] ~ ~ ~ function vanilla/piston
execute @a[scores={t=232}] ~ ~ ~ function vanilla/pistonArmCollision
execute @a[scores={t=233}] ~ ~ ~ function vanilla/planks
execute @a[scores={t=234}] ~ ~ ~ function vanilla/podzol
execute @a[scores={t=235}] ~ ~ ~ function vanilla/polished_andesite_stairs
execute @a[scores={t=236}] ~ ~ ~ function vanilla/polished_diorite_stairs
execute @a[scores={t=237}] ~ ~ ~ function vanilla/polished_granite_stairs
execute @a[scores={t=238}] ~ ~ ~ function vanilla/portal
execute @a[scores={t=239}] ~ ~ ~ function vanilla/potatoes
execute @a[scores={t=240}] ~ ~ ~ function vanilla/powered_comparator
execute @a[scores={t=241}] ~ ~ ~ function vanilla/powered_repeater
execute @a[scores={t=242}] ~ ~ ~ function vanilla/prismarine
execute @a[scores={t=243}] ~ ~ ~ function vanilla/prismarine_bricks_stairs
execute @a[scores={t=244}] ~ ~ ~ function vanilla/prismarine_stairs
execute @a[scores={t=245}] ~ ~ ~ function vanilla/pumpkin
execute @a[scores={t=246}] ~ ~ ~ function vanilla/pumpkin_stem
execute @a[scores={t=247}] ~ ~ ~ function vanilla/purple_glazed_terracotta
execute @a[scores={t=248}] ~ ~ ~ function vanilla/purpur_block
execute @a[scores={t=248}] ~ ~ ~ function vanilla/purpur_stairs
execute @a[scores={t=249}] ~ ~ ~ function vanilla/quartz_block
execute @a[scores={t=250}] ~ ~ ~ function vanilla/quartz_ore
execute @a[scores={t=251}] ~ ~ ~ function vanilla/quartz_stairs
execute @a[scores={t=252}] ~ ~ ~ function vanilla/rail
execute @a[scores={t=253}] ~ ~ ~ function vanilla/red_flower
execute @a[scores={t=254}] ~ ~ ~ function vanilla/red_glazed_terracotta
execute @a[scores={t=255}] ~ ~ ~ function vanilla/red_mushroom
execute @a[scores={t=256}] ~ ~ ~ function vanilla/red_mushroom_block
execute @a[scores={t=257}] ~ ~ ~ function vanilla/red_nether_brick
execute @a[scores={t=258}] ~ ~ ~ function vanilla/red_nether_brick_stairs
execute @a[scores={t=259}] ~ ~ ~ function vanilla/red_sandstone
execute @a[scores={t=260}] ~ ~ ~ function vanilla/red_sandstone_stairs
execute @a[scores={t=261}] ~ ~ ~ function vanilla/redstone_block
execute @a[scores={t=262}] ~ ~ ~ function vanilla/redstone_lamp
execute @a[scores={t=263}] ~ ~ ~ function vanilla/redstone_ore
execute @a[scores={t=264}] ~ ~ ~ function vanilla/redstone_torch
execute @a[scores={t=264}] ~ ~ ~ function vanilla/redstone_wire
execute @a[scores={t=265}] ~ ~ ~ function vanilla/reeds
execute @a[scores={t=266}] ~ ~ ~ function vanilla/repeating_command_block
execute @a[scores={t=267}] ~ ~ ~ function vanilla/reserved6
execute @a[scores={t=268}] ~ ~ ~ function vanilla/sand
execute @a[scores={t=269}] ~ ~ ~ function vanilla/sandstone
execute @a[scores={t=270}] ~ ~ ~ function vanilla/sandstone_stairs
execute @a[scores={t=271}] ~ ~ ~ function vanilla/sapling
execute @a[scores={t=272}] ~ ~ ~ function vanilla/scaffolding
execute @a[scores={t=273}] ~ ~ ~ function vanilla/sea_pickle
execute @a[scores={t=274}] ~ ~ ~ function vanilla/seagrass
execute @a[scores={t=275}] ~ ~ ~ function vanilla/seaLantern
execute @a[scores={t=276}] ~ ~ ~ function vanilla/shulker_box
execute @a[scores={t=277}] ~ ~ ~ function vanilla/silver_glazed_terracotta
execute @a[scores={t=278}] ~ ~ ~ function vanilla/skull
execute @a[scores={t=279}] ~ ~ ~ function vanilla/slime
execute @a[scores={t=280}] ~ ~ ~ function vanilla/smithing_table
execute @a[scores={t=280}] ~ ~ ~ function vanilla/smoker
execute @a[scores={t=281}] ~ ~ ~ function vanilla/smooth_quartz_stairs
execute @a[scores={t=282}] ~ ~ ~ function vanilla/smooth_red_sandstone_stairs
execute @a[scores={t=283}] ~ ~ ~ function vanilla/smooth_sandstone_stairs
execute @a[scores={t=284}] ~ ~ ~ function vanilla/smooth_stone
execute @a[scores={t=285}] ~ ~ ~ function vanilla/snow
execute @a[scores={t=286}] ~ ~ ~ function vanilla/snow_layer
execute @a[scores={t=287}] ~ ~ ~ function vanilla/soul_sand
execute @a[scores={t=288}] ~ ~ ~ function vanilla/sponge
execute @a[scores={t=289}] ~ ~ ~ function vanilla/spruce_button
execute @a[scores={t=290}] ~ ~ ~ function vanilla/spruce_door
execute @a[scores={t=291}] ~ ~ ~ function vanilla/spruce_fence_gate
execute @a[scores={t=292}] ~ ~ ~ function vanilla/spruce_pressure_plate
execute @a[scores={t=293}] ~ ~ ~ function vanilla/spruce_stairs
execute @a[scores={t=294}] ~ ~ ~ function vanilla/spruce_standing_sign
execute @a[scores={t=295}] ~ ~ ~ function vanilla/spruce_trapdoor
execute @a[scores={t=296}] ~ ~ ~ function vanilla/spruce_wall_sign
execute @a[scores={t=296}] ~ ~ ~ function vanilla/stained_glass
execute @a[scores={t=297}] ~ ~ ~ function vanilla/stained_glass_pane
execute @a[scores={t=298}] ~ ~ ~ function vanilla/stained_hardened_clay
execute @a[scores={t=299}] ~ ~ ~ function vanilla/standing_banner
execute @a[scores={t=300}] ~ ~ ~ function vanilla/standing_sign
execute @a[scores={t=301}] ~ ~ ~ function vanilla/sticky_piston
execute @a[scores={t=302}] ~ ~ ~ function vanilla/stone
execute @a[scores={t=303}] ~ ~ ~ function vanilla/stone_brick_stairs
execute @a[scores={t=304}] ~ ~ ~ function vanilla/stone_button
execute @a[scores={t=305}] ~ ~ ~ function vanilla/stone_pressure_plate
execute @a[scores={t=306}] ~ ~ ~ function vanilla/stone_slab
execute @a[scores={t=307}] ~ ~ ~ function vanilla/stone_slab2
execute @a[scores={t=308}] ~ ~ ~ function vanilla/stone_slab3
execute @a[scores={t=309}] ~ ~ ~ function vanilla/stone_slab4
execute @a[scores={t=310}] ~ ~ ~ function vanilla/stone_stairs
execute @a[scores={t=311}] ~ ~ ~ function vanilla/stonebrick
execute @a[scores={t=312}] ~ ~ ~ function vanilla/stonecutter
execute @a[scores={t=312}] ~ ~ ~ function vanilla/stripped_acacia_log
execute @a[scores={t=313}] ~ ~ ~ function vanilla/stripped_birch_log
execute @a[scores={t=314}] ~ ~ ~ function vanilla/stripped_dark_oak_log
execute @a[scores={t=315}] ~ ~ ~ function vanilla/stripped_jungle_log
execute @a[scores={t=316}] ~ ~ ~ function vanilla/stripped_oak_log
execute @a[scores={t=317}] ~ ~ ~ function vanilla/stripped_spruce_log
execute @a[scores={t=318}] ~ ~ ~ function vanilla/structure_block
execute @a[scores={t=319}] ~ ~ ~ function vanilla/structure_void
execute @a[scores={t=320}] ~ ~ ~ function vanilla/tallgrass
execute @a[scores={t=321}] ~ ~ ~ function vanilla/tnt
execute @a[scores={t=322}] ~ ~ ~ function vanilla/torch
execute @a[scores={t=323}] ~ ~ ~ function vanilla/trapdoor
execute @a[scores={t=324}] ~ ~ ~ function vanilla/trapped_chest
execute @a[scores={t=325}] ~ ~ ~ function vanilla/tripWire
execute @a[scores={t=326}] ~ ~ ~ function vanilla/tripwire_hook
execute @a[scores={t=327}] ~ ~ ~ function vanilla/turtle_egg
execute @a[scores={t=328}] ~ ~ ~ function vanilla/undyed_shulker_box
execute @a[scores={t=328}] ~ ~ ~ function vanilla/unlit_redstone_torch
execute @a[scores={t=329}] ~ ~ ~ function vanilla/unpowered_comparator
execute @a[scores={t=330}] ~ ~ ~ function vanilla/unpowered_repeater
execute @a[scores={t=331}] ~ ~ ~ function vanilla/vine
execute @a[scores={t=332}] ~ ~ ~ function vanilla/wall_banner
execute @a[scores={t=333}] ~ ~ ~ function vanilla/wall_sign
execute @a[scores={t=334}] ~ ~ ~ function vanilla/water
execute @a[scores={t=335}] ~ ~ ~ function vanilla/waterlily
execute @a[scores={t=336}] ~ ~ ~ function vanilla/web
execute @a[scores={t=337}] ~ ~ ~ function vanilla/wheat
execute @a[scores={t=338}] ~ ~ ~ function vanilla/white_glazed_terracotta
execute @a[scores={t=339}] ~ ~ ~ function vanilla/wooden_button
execute @a[scores={t=340}] ~ ~ ~ function vanilla/wooden_door
execute @a[scores={t=341}] ~ ~ ~ function vanilla/wooden_pressure_plate
execute @a[scores={t=342}] ~ ~ ~ function vanilla/wooden_slab
execute @a[scores={t=343}] ~ ~ ~ function vanilla/wool
execute @a[scores={t=344}] ~ ~ ~ function vanilla/yellow_flower
execute @a[scores={t=344}] ~ ~ ~ function vanilla/yellow_glazed_terracotta
scoreboard players add @a t 1