execute @a[scores={t=2}] ~ ~ ~ fill ~ ~-2 ~ ~4 ~-2 ~16 chest
tp @a[scores={t=..85}] ~ ~1 ~
execute @a[scores={t=41}] ~ ~ ~ function vanilla_1.16/ancient_debris
execute @a[scores={t=42}] ~ ~ ~ function vanilla_1.16/basalt_block
execute @a[scores={t=43}] ~ ~ ~ function vanilla_1.16/blue_fire
execute @a[scores={t=44}] ~ ~ ~ function vanilla_1.16/blue_nether_wart_block
execute @a[scores={t=45}] ~ ~ ~ function vanilla_1.16/crimson_button
execute @a[scores={t=46}] ~ ~ ~ function vanilla_1.16/crimson_door
execute @a[scores={t=47}] ~ ~ ~ function vanilla_1.16/crimson_double_slab
execute @a[scores={t=48}] ~ ~ ~ function vanilla_1.16/crimson_fence
execute @a[scores={t=49}] ~ ~ ~ function vanilla_1.16/crimson_fence_gate
execute @a[scores={t=50}] ~ ~ ~ function vanilla_1.16/crimson_fungus
execute @a[scores={t=51}] ~ ~ ~ function vanilla_1.16/crimson_nylium
execute @a[scores={t=52}] ~ ~ ~ function vanilla_1.16/crimson_planks
execute @a[scores={t=53}] ~ ~ ~ function vanilla_1.16/crimson_pressure_plate
execute @a[scores={t=54}] ~ ~ ~ function vanilla_1.16/crimson_roots
execute @a[scores={t=55}] ~ ~ ~ function vanilla_1.16/crimson_slab
execute @a[scores={t=56}] ~ ~ ~ function vanilla_1.16/crimson_stairs
execute @a[scores={t=56}] ~ ~ ~ function vanilla_1.16/crimson_standing_sign
execute @a[scores={t=57}] ~ ~ ~ function vanilla_1.16/crimson_stem
execute @a[scores={t=58}] ~ ~ ~ function vanilla_1.16/crimson_trap_door
execute @a[scores={t=59}] ~ ~ ~ function vanilla_1.16/crimson_wall_sign
execute @a[scores={t=60}] ~ ~ ~ function vanilla_1.16/nether_sprouts
execute @a[scores={t=61}] ~ ~ ~ function vanilla_1.16/netherite_block
execute @a[scores={t=62}] ~ ~ ~ function vanilla_1.16/polished_basalt_block
execute @a[scores={t=63}] ~ ~ ~ function vanilla_1.16/shroomlight_block
execute @a[scores={t=64}] ~ ~ ~ function vanilla_1.16/soul_lantern
execute @a[scores={t=65}] ~ ~ ~ function vanilla_1.16/soul_soil_block
execute @a[scores={t=66}] ~ ~ ~ function vanilla_1.16/soul_torch
execute @a[scores={t=67}] ~ ~ ~ function vanilla_1.16/stripped_crimson_stem
execute @a[scores={t=68}] ~ ~ ~ function vanilla_1.16/stripped_warped_stem
execute @a[scores={t=69}] ~ ~ ~ function vanilla_1.16/target_block
execute @a[scores={t=70}] ~ ~ ~ function vanilla_1.16/warped_button
execute @a[scores={t=71}] ~ ~ ~ function vanilla_1.16/warped_door
execute @a[scores={t=72}] ~ ~ ~ function vanilla_1.16/warped_double_slab
execute @a[scores={t=72}] ~ ~ ~ function vanilla_1.16/warped_fence
execute @a[scores={t=73}] ~ ~ ~ function vanilla_1.16/warped_fence_gate
execute @a[scores={t=74}] ~ ~ ~ function vanilla_1.16/warped_fungus
execute @a[scores={t=75}] ~ ~ ~ function vanilla_1.16/warped_nylium
execute @a[scores={t=76}] ~ ~ ~ function vanilla_1.16/warped_planks
execute @a[scores={t=77}] ~ ~ ~ function vanilla_1.16/warped_pressure_plate
execute @a[scores={t=78}] ~ ~ ~ function vanilla_1.16/warped_roots
execute @a[scores={t=79}] ~ ~ ~ function vanilla_1.16/warped_slab
execute @a[scores={t=80}] ~ ~ ~ function vanilla_1.16/warped_stairs
execute @a[scores={t=81}] ~ ~ ~ function vanilla_1.16/warped_standing_sign
execute @a[scores={t=82}] ~ ~ ~ function vanilla_1.16/warped_stem
execute @a[scores={t=83}] ~ ~ ~ function vanilla_1.16/warped_trapdoor
execute @a[scores={t=84}] ~ ~ ~ function vanilla_1.16/warped_wall_sign
execute @a[scores={t=85}] ~ ~ ~ function vanilla_1.16/weeping_vines_block
scoreboard players add @a t 1